# Phundament 4 - Potemkin Testing Stack
# =====================================

# Note: Wait until `appcli` container has completed its startup.

# Spawn a new project locally
#
#   docker-compose run appsrc cp -r /phundament-src/src /mnt
#   docker-compose up -d
#   docker-compose run appcli ../yii

# Application services
# --------------------

# container to run one-off commands - a dockerized shell
appcli:
  command: 'sh /app/src/run.sh'
  # should be replaced with: image: <project_name>_appsrc
  image: phundament/app:4.0.0-rc1-dev
  links:
    - 'appnginx:WEB'
    - 'mariadb:DB'
    - 'seleniumhub:HUB'
  volumes:
    - ../:/app/vendor/bedezign/yii2-audit
    - _config/local.php:/app/src/config/local.php
  volumes_from:
    - appsrc
  environment:
    DB_ENV_MYSQL_DATABASE: audit-test
    APP_MIGRATION_LOOKUP: '@app/migrations'

appsrc:
  image: phundament/app:4.0.0-rc1-dev
  volumes:
    - ../:/app/vendor/bedezign/yii2-audit
    - _config/local.php:/app/src/config/local.php
    - '/app'
  command: 'tail -f /dev/null'

# The php-fpm server for interpreting php code
appfpm:
  environment:
    DB_ENV_MYSQL_DATABASE: audit-test
  image: phundament/php:5.6-fpm-4.0.0-rc1-dev
  # host-volume for local development
  volumes:
    - ../:/app/vendor/bedezign/yii2-audit
    - _config/local.php:/app/src/config/local.php
  volumes_from:
    - appsrc
  links:
    - 'mariadb:DB'

# The nginx server for serving static files directly
appnginx:
  image: schmunk42/nginx:1.7
  links:
    - 'appfpm:PHPFPM'
  # host-volume for local development
  volumes:
    - ../:/app/vendor/bedezign/yii2-audit
  volumes_from:
    - appsrc
  ports:
    - '80'
  environment:
    VIRTUAL_HOST: '~^test\.audit\.'

# Data Services
# -------------

mariadb:
  image: tutum/mariadb:10.1
  ports:
    - '3306'
  environment:
    MARIADB_PASS: secretadmin

#redis:
#    image: redis:3.0
#    ports:
#      - 6379

# Testing Services
# ----------------

seleniumchrome:
    image: 'selenium/node-chrome-debug:2.46.0'
    links:
        - 'appnginx:WEB'
        - 'seleniumhub:HUB'
    ports:
        - '5900'
seleniumfirefox:
    image: 'selenium/node-firefox-debug:2.46.0'
    links:
        - 'appnginx:WEB'
        - 'seleniumhub:HUB'
    ports:
        - '5900'
seleniumhub:
    image: 'selenium/hub:2.46.0'
    ports:
        - '4444'
