# Docker compose configuration for tutum deployment

# The nginx server for serving static files directly, cached contents via the memcached server and php files via the php service
%VIRTUAL_HOST_BASED_WEB_SERVICE_NAME%: # A unique service name makes it easier to identify in tutum ui and api
  image: tutum.co/%TUTUM_USER%/%REPO%-nginx:git-commit-%COMMITSHA%
  links:
    - phphaproxy
    - phpfiles
#    - memcached
  ports:
    - "80"
  environment:
    NGINX_ERROR_LOG_LEVEL: 'notice'
    VIRTUAL_HOST: '%VIRTUAL_HOST%'
    # The haproxy router is configured to respond to port 80 without ssl, thus we need to make sure that proxying to the web service's port 443 is not attempted
    # A separate haproxy and corresponding web service needs to be set up to respond to port 443 with ssl if required
    EXCLUDE_PORTS: 443
%ENVIRONMENT_YAML%
  command: "/app/stack/nginx/run.sh"
  # Set cluster deploy tags to ensure this container is launched inside a cluster and not on a publicly facing node)
  tags:
    - ec-%DEPLOY_STABILITY_TAG%
    - not-files-%DEPLOY_STABILITY_TAG%
  # Auto-restart in case container dies unexpectedly
  autorestart: always
  # Do not update the service when a new version is pushed to the registry (whole stack is redeployed when necessary)
  autoredeploy: false
  # Seqential deployment so that changes can be re-deployed without too much service interruption
  sequential_deployment: true
  # Container distribution among nodes
  deployment_strategy: high_availability

# HA Proxy for php service scaling
phphaproxy:
  image: neam/tutum-haproxy:a1e506f
  links:
    - phpha
  ports:
    - "9000"
    # Publish stats port
    - "1936"
  environment:
    MODE: tcp
    TIMEOUT: connect 5000, client 50000, server 50000
    # Some sort of protection for the stats endpoint (needless to say, you should use a unique secure password in production)
    STATS_AUTH: stats:n3v3rg0nnAg1v3y0uup
  # Set cluster deploy tags to ensure this container is launched inside a cluster and not on a publicly facing node)
  tags:
    - ec-%DEPLOY_STABILITY_TAG%
    - not-files-%DEPLOY_STABILITY_TAG%
  # Auto-restart in case container dies unexpectedly
  autorestart: always
  # Do not update the service when a new version is pushed to the registry (whole stack is redeployed when necessary)
  autoredeploy: false
  # Container distribution among nodes
  deployment_strategy: high_availability
  # Enable full Tutum API access so that the container can reconfigure itself
  roles:
      - global

# The elastically scalable php service for interpreting php code without access to /files
phpha:
  image: tutum.co/%TUTUM_USER%/%REPO%-php:git-commit-%COMMITSHA%
  links:
    - mailcatcher
    - redisphpsessionhandler
#    - memcached
  ports:
    - "9000"
  environment:
    TCP_PORTS: '9000'
    DISPLAY_PHP_ERRORS: 'off'
    XDEBUG_DEFAULT_ENABLE: 'off'
%ENVIRONMENT_YAML%
  working_dir: '/app'
  command: "/app/stack/php/run.sh"
  # Set cluster deploy tags to ensure this container is launched inside a cluster and not on a publicly facing node)
  tags:
    - ec-%DEPLOY_STABILITY_TAG%
    - not-files-%DEPLOY_STABILITY_TAG%
  # Auto-restart in case container dies unexpectedly
  autorestart: always
  # Do not update the service when a new version is pushed to the registry (whole stack is redeployed when necessary)
  autoredeploy: false
  # Seqential deployment so that changes can be re-deployed without too much service interruption
  sequential_deployment: true
  # Container distribution among nodes
  deployment_strategy: high_availability

redisphpsessionhandler:
  image: redis
  ports:
   - "6379"
  # Set cluster deploy tags to ensure this container is launched inside a cluster and not on a publicly facing node)
  tags:
    - ec-%DEPLOY_STABILITY_TAG%
    - not-files-%DEPLOY_STABILITY_TAG%
  # Auto-restart in case container dies unexpectedly
  autorestart: always
  # Do not update the service when a new version is pushed to the registry (whole stack is redeployed when necessary)
  autoredeploy: false

# The single-node php service for interpreting php code with read-write access to user-generated files
# (to support file uploads and other local file manipulations)
phpfiles:
  image: tutum.co/%TUTUM_USER%/%REPO%-php:git-commit-%COMMITSHA%
  links:
    - mailcatcher
    - redisphpsessionhandler
#    - memcached
  volumes:
    - /files
  ports:
   - "9000"
  environment:
    DISPLAY_PHP_ERRORS: 'off'
    XDEBUG_DEFAULT_ENABLE: 'off'
%ENVIRONMENT_YAML%
  working_dir: '/app'
  command: "/app/stack/php/run.sh"
  # Set cluster deploy tags to ensure this container is launched inside a cluster and not on a publicly facing node)
  tags:
    - ec-%DEPLOY_STABILITY_TAG%
    - files-%DEPLOY_STABILITY_TAG%
  # Auto-restart in case container dies unexpectedly
  autorestart: always
  # Do not update the service when a new version is pushed to the registry (whole stack is redeployed when necessary)
  autoredeploy: false
  # Container distribution among nodes
  deployment_strategy: emptiest_node

# Memcached server for serving cached contents via the nginx-memcache plugin
#memcached:
#  image: memcached:1.4.22
#  ports:
#    - "11211"

# Mailcatcher server for catching outgoing email when not in production
mailcatcher:
  image: nisenabe/mailcatcher
  expose:
    - "25"
  ports:
    - "1080"
  # Set cluster deploy tags to ensure this container is launched inside a cluster and not on a publicly facing node)
  tags:
    - ec-%DEPLOY_STABILITY_TAG%
    - not-files-%DEPLOY_STABILITY_TAG%
  # Auto-restart in case container dies unexpectedly
  autorestart: always
  # Do not update the service when a new version is pushed to the registry (whole stack is redeployed when necessary)
  autoredeploy: false

# Selenium...
