web:
  image: tutum/haproxy
  links:
    - plantuml:plantuml
    - scruffy:scruffy
  ports:
    - "80"

plantuml:
  image: neam/plantuml-server
  environment:
    - VIRTUAL_HOST: 'plantuml-server.example.com'

scruffy:
  image: neam/scruffy-server
  environment:
    - VIRTUAL_HOST: 'scruffy-server.example.com'
